package org.sagebionetworks.bridge.models.studies;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;

import org.sagebionetworks.bridge.json.BridgeObjectMapper;

public class MimeTypeTest {

    @Test
    public void canDeserializeAutogeneratedMimeTypes() throws Exception {
        MimeType deser = BridgeObjectMapper.get().readValue("\"pdf\"", MimeType.class);
        assertEquals(MimeType.PDF, deser);
        
        deser = BridgeObjectMapper.get().readValue("\"application/pdf\"", MimeType.class);
        assertEquals(MimeType.PDF, deser);
        
        deser = BridgeObjectMapper.get().readValue("\"HTML\"", MimeType.class);
        assertEquals(MimeType.HTML, deser);
        
        deser = BridgeObjectMapper.get().readValue("\"TEXT/PLAIN\"", MimeType.class);
        assertEquals(MimeType.TEXT, deser);
    }
    
    @Test
    public void nullDoesNotBreakDeserialization() throws Exception {
        assertNull(BridgeObjectMapper.get().readValue("\"\"", MimeType.class));
    }
}
