package org.sagebionetworks.bridge.models.upload;

import java.util.List;

import org.joda.time.LocalDate;

/** Metadata for Bridge uploads. */
public interface Upload {
    /**
     * If the upload is in a state where calling uploadComplete() and kicking off validation is a valid thing to do,
     * then this method will return true. Otherwise, this method will return false.
     */
    boolean canBeValidated();

    /** Name of the file to upload. */
    String getFilename();

    /** Health code of the user from which this upload originates from. */
    String getHealthCode();

    /**
     * S3 object ID (key name). This is generated by Bridge to ensure no filename collisions and to ensure that we
     * don't get S3 hotspots from poorly distributed names.
     */
    String getObjectId();

    /** Represents upload status, such as requested, validation in progress, validation failed, or succeeded. */
    UploadStatus getStatus();

    /**
     * Calendar date the file was uploaded (specifically, the uploadComplete() call. Date is determined using Pacific
     * local time.
     */
    LocalDate getUploadDate();

    /** Upload ID. This is the key in the Dynamo DB table that uniquely identifies this upload. */
    String getUploadId();

    /** List of validation messages, generally contains error messages. */
    List<String> getValidationMessageList();
}
