package org.sagebionetworks.bridge.models.upload;

/** Metadata for Bridge uploads. */
public interface Upload {

    /** Upload ID. This is the key in the Dynamo DB table that uniquely identifies this upload. */
    String getUploadId();

    /**
     * S3 object ID (key name). This is generated by Bridge to ensure no filename collisions and to ensure that we
     * don't get S3 hotspots from poorly distributed names.
     */
    // TODO: This is being merged with Upload ID. Delete this field when the migration is complete.
    String getObjectId();

    /** True if the upload is complete. False otherwise. */
    boolean isComplete();
}
