package org.sagebionetworks.bridge.models.accounts;

import org.joda.time.DateTime;

import org.sagebionetworks.bridge.hibernate.HibernateAccountSecret;

/**
 * A password or passphrase, either provided by the user or autogenerated, that can be 
 * submitted with a credential to authenticate the user. The value is stored hashed 
 * using the algorithm indicated by the password algorithm. 
 */
public interface AccountSecret {
    
    static AccountSecret create() {
        return new HibernateAccountSecret();
    }
    
    String getAccountId();
    void setAccountId(String accountId);
    
    AccountSecretType getType();
    void setType(AccountSecretType type);
    
    PasswordAlgorithm getAlgorithm();
    void setAlgorithm(PasswordAlgorithm algorithm);
    
    String getHash();
    void setHash(String hash);
    
    DateTime getCreatedOn();
    void setCreatedOn(DateTime createdOn);
}
