package org.sagebionetworks.bridge.models.accounts;

public enum SharingScope {
    /**
     * Don't export data generated by this participant.
     */
    NO_SHARING("Not Sharing"),
    /**
     * Only export participant's data to a data set for the original study researchers and their affiliated research
     * partners.
     */
    SPONSORS_AND_PARTNERS("Sponsors and Partners Only"),
    /**
     * Export participant's data to a data set that can be used by any researcher who qualifies given the governance
     * qualifications of this data set.
     */
    ALL_QUALIFIED_RESEARCHERS("All Qualified Researchers");
    
    private final String label;
    
    SharingScope(String label) {
        this.label = label;
    }
    public String getLabel() {
        return label;
    }
}