package org.sagebionetworks.bridge.dao;

public enum ParticipantOption {

    SHARING_SCOPE(SharingScope.NO_SHARING.name());
    
    private final String defaultValue;
    
    private ParticipantOption(String defaultValue) {
        this.defaultValue = defaultValue;
    }
    
    public String getDefaultValue() {
        return defaultValue;
    }

    public enum SharingScope {
        /**
         * Don't export data generated by this participant.
         */
        NO_SHARING,
        /**
         * Only export participant's data to a data set for the original study researchers and their affiliated research
         * partners.
         */
        SPONSORS_AND_PARTNERS_ONLY,
        /**
         * Export participant's data to a data set that can be used by any researcher who qualifies given the governance
         * qualifications of this data set.
         */
        ALL_QUALIFIED_RESEARCHERS
    }
   
}
