package org.sagebionetworks.bridge.dao;

public enum ParticipantOption {

    @Deprecated
    DATA_SHARING("true"),
    SCOPE_OF_SHARING(ScopeOfSharing.NO_SHARING.name());
    
    private final String defaultValue;
    
    private ParticipantOption(String defaultValue) {
        this.defaultValue = defaultValue;
    }
    
    public String getDefaultValue() {
        return defaultValue;
    }

    public enum ScopeOfSharing {
        /**
         * Don't export data generated by this participant.
         */
        NO_SHARING,
        /**
         * Only export data for this participant to data sets that are restricted to the original 
         * study researchers and their affiliated research partners.
         */
        SPONSORS_AND_PARTNERS,
        /**
         * Data for this participant can be exported for use by any researcher who qualifies given
         * the governance qualifications of this data set.
         */
        ALL_QUALIFIED_RESEARCHERS
    }
   
}
